baseurl = "http://h6ah4i.com/android-advancedrecyclerview/"
languageCode = "en-us"
title = "Advanced RecyclerView"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""
enableEmoji = true

[params]
    # General information
    author = "Haruki Hasegawa (@h6ah4i)"
    description = "Documentation for Advanced RecyclerView library."
    copyright = "Haruki Hasegawa"

    # Repository
    provider = "GitHub"
    repo_url = "https://github.com/h6ah4i/android-advancedrecyclerview"

    version = "0.9.3"
    logo = "images/logo.png"
    favicon = ""

    permalink = "#"

    # Custom assets
    custom_css = ["stylesheets/overrides.css"]
    custom_js  = ["vendor/highlight/highlight.pack.js"]

    # Syntax highlighting theme
    highlight_css  = "vendor/highlight/styles/github.css"

    [params.palette]
        primary = "blue-grey"
        accent  = "orange"

    [params.font]
        text = "Roboto"
        code = "Roboto Mono"


[social]
    twitter = ""
    github  = "h6ah4i"


[[menu.main]]
    name   = "Home"
    url    = "/"
    weight = 0

[[menu.main]]
    name   = "Getting started"
    url    = "getting-started/"
    weight = 10

[[menu.main]]
    name   = "Wrapper Adapter"
    url    = "wrapper-adapter/"
    weight = 20

[[menu.main]]
    name   = "Draggable"
    url    = "draggable/"
    weight = 21

[[menu.main]]
    name   = "Swipeable"
    url    = "swipeable/"
    weight = 22

[[menu.main]]
    name   = "Expandable"
    url    = "expandable/"
    weight = 23

[[menu.main]]
    name   = "Advanced Examples"
    url    = "advanced-examples/"
    weight = 24

[[menu.main]]
    name   = "FAQ"
    url    = "faq/"
    weight = 30

[[menu.main]]
    name   = "License"
    url    = "license/"
    weight = 40


[blackfriday]
    smartypants = true
    fractions = true
    smartDashes = true
    plainIDAnchors = true
